# Generated by Django 4.2 on 2024-11-06 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_profile_options_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-applied_date']},
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Loan amount must be greater than zero'), django.core.validators.MaxValueValidator(1000000, message='Loan amount cannot exceed ₦1,000,000')]),
        ),
    ]
